const CodeSkills = [
  "Authorization",
  "AWS",
  "Back-End Web Development",
  "Collaboration",
  "Critical Thinking",
  "CSS",
  "Data Entry",
  "Detail Oriented",
  "Docker",
  "Drupal",
  "Encryption",
  "Express",
  "File Management",
  "Front-End Web Development",
  "Full-Stack Web Development",
  "Git",
  "GitHub",
  "Heroku",
  "HTML",
  "Information Technology",
  "JavaScript",
  "Multitasking",
  "Node",
  "Prioritization",
  "Problem-Solving",
  "Project Management",
  "Quality Assurance",
  "React",
  "Research",
  "SQL",
  "Terminal",
  "Verbal and Written Communication",
  "Vercel",
  "Vite",
  "Wireframing",
  "Workflow Optimization",
];

export default CodeSkills;
