const VideoSkills = [
  "Adobe After Effects",
  "Adobe Audition",
  "Adobe Illustrator",
  "Adobe Media Encoder",
  "Adobe Photoshop",
  "Adobe Premiere Pro",
  "Archiving",
  "Asana",
  "Avid Media Composer",
  "Camera Operation",
  "CapCut",
  "Client Relations",
  "Codecs",
  "Collaboration",
  "Color Correction",
  "Creative Direction",
  "Critical Thinking",
  "Data Entry",
  "DaVinci Resolve",
  "Detail Oriented",
  "Digitization",
  "Directing",
  "Drupal",
  "FFmpeg",
  "File Management",
  "Final Cut Pro",
  "Handbrake",
  "iMovie",
  "Keying",
  "Media Asset Management",
  "Metadata",
  "Microsoft Office",
  "Motion Design",
  "Motion Tracking",
  "Multitasking",
  "Photo Retouching",
  "Post-Production",
  "Pre-Production",
  "Prioritization",
  "Problem-Solving",
  "Production",
  "Project Management",
  "Quality Assurance",
  "Remote Server Operation",
  "Research",
  "Rotoscoping",
  "Storyboarding",
  "Terminal",
  "TikTok",
  "Transcoding",
  "Verbal and Written Communication",
  "Video Editing",
  "Vimeo",
  "Web Streaming",
  "Workflow Optimization",
  "X/Twitter",
  "YouTube",
];

export default VideoSkills;
