const VideoSkills = [
  "Adobe After Effects, Audition, Illustrator, Media Encoder, Photoshop, Premiere",
  "Archiving",
  "Camera Operation",
  "Codecs",
  "Collaboration",
  "Color Correction",
  "Critical Thinking",
  "Detail Oriented",
  "Digitization",
  "Excel",
  "FFmpeg",
  "File Management",
  "Handbrake",
  "Keying",
  "Motion Design",
  "Multitasking",
  "Photo Retouching",
  "Pre-Production",
  "Prioritization",
  "Problem Solving",
  "Project Management",
  "Post-Production",
  "Quality Assurance",
  "Research",
  "Remote Server Operation",
  "Rotoscoping",
  "Storyboarding",
  "TikTok",
  "Terminal",
  "Tracking",
  "Transcoding",
  "Verbal and Written Communication",
  "Video Editing",
  "Vimeo",
  "Web Streaming",
  "Workflow Optimization",
  "X/Twitter",
  "YouTube",
];

export default VideoSkills;
